name: ğŸ”§ Config
description: í™˜ê²½ ì„¤ì •, ì˜ì¡´ì„±, ë¹Œë“œ ê´€ë ¨ ë³€ê²½ ì‚¬í•­ì„ ê³µìœ í•´ì£¼ì„¸ìš”.
title: "[config] "
labels: ["ğŸ”§ config"]
body:
  - type: textarea
    id: file
    attributes:
      label: ì„¤ì • íŒŒì¼
      description: ì–´ë–¤ ì„¤ì • íŒŒì¼ì´ ë³€ê²½ë˜ì—ˆë‚˜ìš”? (ì˜ˆ: gradle, lint ë“±)

  - type: textarea
    id: reason
    attributes:
      label: ë³€ê²½ ì´ìœ 
      description: ì´ ë³€ê²½ì´ í•„ìš”í•œ ì´ìœ ë¥¼ ì„¤ëª…í•´ì£¼ì„¸ìš”.

  - type: textarea
    id: note
    attributes:
      label: ì°¸ê³  ì‚¬í•­
      description: íŒ€ì›ì—ê²Œ ê³µìœ í•´ì•¼ í•  ì¶”ê°€ ì •ë³´ê°€ ìˆë‹¤ë©´ ì‘ì„±í•´ì£¼ì„¸ìš”.
